# Generated by Django 2.1 on 2019-02-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(upload_to='carsf'),
        ),
    ]
