# Generated by Django 2.1 on 2019-02-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20190208_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, upload_to='carsf/'),
        ),
    ]
